config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "articles#index"

  resources :users, only: %i[new create], defaults: { format: :html }
  resources :sessions, only: %i[new create destroy], defaults: { format: :html }

  resources :articles, only: %i[create destroy index], defaults: { format: :html } do
    collection do
      get ":country", to: "articles#index", as: "country"
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:create]
      resources :sessions, only: %i[create destroy]
      resources :articles, only: %i[create destroy index] do
        collection do
          get ":country", to: "articles#index", as: "api_country"
        end
      end
    end
  end
end

app/models/article.rb
# frozen_string_literal: true

# Represents an article in the application.
class Article < ApplicationRecord
  belongs_to :user
end

app/controllers/api/v1/articles_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # This is a ArticlesController responsible for managing article-related actions.
    class ArticlesController < ApplicationController
      before_action :signed_in_user

      def index
        articles = current_user.articles
        country_code = fetch_country_code
        news_service = NewsApi.new(country_code)
        live_articles = news_service.call

        respond_to do |format|
          format.json { render json: { saved_headlines: articles, headlines: live_articles }, status: :ok }
        end
      end

      def create
        article = build_article
        return unless article.save

        handle_successful("saved", :created, article)
      end

      def destroy
        article = Article.find_by(id: params[:id])

        if article&.destroy
          handle_successful("deleted", nil, article)
        elsif article.nil?
          handle_not_found "Headline not found"
        end
      end

      private

      def fetch_country_code
        (params[:country] || current_user.country_code).downcase
      end

      def build_article
        current_user.articles.build(articles_params).tap do |article|
          article.user = current_user
        end
      end

      def handle_successful(item, status, article)
        Rails.logger.info("Headline successfully #{item}")

        respond_to do |format|
          format.json do
            render json: { message: "Headline successfully #{item}", headline: article }, status:
          end
        end
      end

      def handle_not_found(message)
        Rails.logger.error message
        respond_to { |format| format.json { render json: { error: message }, status: :unprocessable_entity } }
      end

      protected

      def articles_params
        params.require(:article).permit(:source, :author, :title, :description, :content, :url, :url_to_image,
                                        :publish_at, :user)
      end
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# This is a ArticlesController responsible for managing article-related actions.
class ArticlesController < ApplicationController
  before_action :signed_in_user

  def index
    articles = current_user.articles
    country_code = fetch_country_code
    news_service = NewsApi.new(country_code)
    live_articles = news_service.call || []

    render locals: { articles:, live_articles:, country_code: }
  end

  def create
    article = build_article
    return unless article.save

    handle_successful("saved")
  end

  def destroy
    article = Article.find_by(id: params[:id])

    if article&.destroy
      handle_successful("deleted")
    elsif article.nil?
      handle_not_found "Headline not found"
    end
  end

  private

  def fetch_country_code
    (params[:country] || current_user.country_code).downcase
  end

  def build_article
    current_user.articles.build(articles_params).tap do |article|
      article.user = current_user
    end
  end

  def handle_successful(item)
    Rails.logger.info("Headline successfully #{item}")

    flash[:success] = "Headline successfully #{item}"
    redirect_to root_path
  end

  def handle_not_found(message)
    Rails.logger.error message
    flash[:error] = message
    redirect_to articles_url
  end

  protected

  def articles_params
    params.require(:article).permit(:source, :author, :title, :description, :content, :url, :url_to_image, :publish_at,
                                    :user)
  end
end

app/views/articles/index.html.erb
<div class="grid grid-cols-2 p-2 gap-6">
  <div class="col-1">
    <h1 class="text-4xl font-bold text-gray-500">Headlines</h1>
    <%= form_with url: articles_path, method: :get, class: 'w-full max-w-sm' do |f| %>
      <div class="flex items-center py-2">
        <%= f.country_select :country, { selected: country_code.upcase }, { include_blank: 'Select a country' }, { class: 'w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none' } %>
        <%= f.submit 'Search', class: 'flex-shrink-0 bg-gray-500 hover:bg-gray-700 border-gray-500 hover:border-gray-700 text-md border-4 text-white py-1 px-2' %>
      </div>
    <% end %>
    <div class="card-group">
      <% unless live_articles.empty? %>
        <% live_articles.each do |article| %>
          <div class="max-w-xl mb-2 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
              <%= image_tag URI.parse(article[:url_to_image] || placeholder_image_news('1100x600')).normalize.to_s, class:"rounded-t-lg", alt:'' %>
            </a>
            <div class="p-5">
              <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= article[:title] %></h5>
              </a>
              <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= article[:description] %></p>
              <div class="flex justify-between ">
                <p class="card-text text-gray-500"><%= article[:source] %></p>
                <% if article[:publish_at] %>
                  <p class="card-text text-gray-500"><%= time_ago_in_words(article[:publish_at]) + " ago" %></p>
                <% end %>
              </div>
              <div class="flex justify-between text-center">
                <%= link_to 'Save', articles_path(article: article), data: {turbo_method: :post}, class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800' %>
                <%= link_to 'Read', article[:url], class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="py-4 font-bold text-gray-500">No Headlines</p>
      <% end %>
    </div>
  </div>
  <div class="col-1">
    <h1 class="text-4xl font-bold text-gray-500">Saved Headlines</h1>
    <div class="card-group mt-14">
      <% unless articles.empty? %>
        <% articles.each do |article| %>
          <div class="max-w-xl mb-2 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
              <%= image_tag URI.parse(article[:url_to_image] || placeholder_image_news("1100x600")).normalize.to_s, class:"rounded-t-lg", alt:'' %>
            </a>
            <div class="p-5">
              <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= article[:title] %></h5>
              </a>
              <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= article[:description] %></p>
              <div class="flex justify-between ">
                <p class="card-text text-gray-500"><%= article[:source] %></p>
                <p class="card-text text-gray-500"><%= time_ago_in_words(article[:publish_at]) + " ago" %></p>
              </div>
              <div class="flex justify-between text-center">
                <%= link_to 'Remove', article_path(article), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this article?' }, class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-700 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800' %>
                <%= link_to 'Read', article[:url], class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No Headlines</p>
      <% end %>
    </div>
  </div>
</div>