config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "articles#index"

  resources :users, only: %i[new create], defaults: { format: :html }
  resources :sessions, only: %i[new create destroy], defaults: { format: :html }

  resources :articles, only: %i[create destroy index], defaults: { format: :html } do
    collection do
      get ":country", to: "articles#index", as: "country"
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:create]
      resources :sessions, only: %i[create destroy]
      resources :articles, only: %i[create destroy index] do
        collection do
          get ":country", to: "articles#index", as: "api_country"
        end
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# Represents a user in the application.
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy

  before_save { |user| user.email = email.downcase if user.email? }
  before_save { |user| user.country_code = country_code.downcase }
  before_save :create_remember_token

  validates :name, presence: true
  validates :email, presence: true
  validates :country_code, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 5, presence: true }

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # This is a UsersController responsible for managing user-related actions.
    class UsersController < ApplicationController
      def create
        user = User.new(user_params)
        if user.save
          sign_in user

          handle_successful_response user

        else
          handle_fail_response user.errors.full_messages.join

        end
      end

      private

      def handle_successful_response(user)
        Rails.logger.info("User successfully registered")
        message = t("flash.success.user")
        respond_to { |format| format.json { render json: { message:, user: }, status: :created } }
      end

      def handle_fail_response(message)
        Rails.logger.error(message)
        respond_to { |format| format.json { render json: { errors: message }, status: :unprocessable_entity } }
      end

      protected

      def user_params
        params.require(:user).permit(:name, :email, :password, :country_code)
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# This is a UsersController responsible for managing user-related actions.
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      sign_in user

      handle_successful_response

    else
      handle_failed user.errors.full_messages.join

    end
  end

  private

  def handle_successful_response
    Rails.logger.info("User successfully registered")

    message = t("flash.success.user")
    flash[:success] = message
    redirect_to root_path
  end

  def handle_failed(message)
    log_error message
    render "new"
  end

  def log_error(message)
    flash[:error] = message
    Rails.logger.error(message)
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password, :country_code)
  end
end

app/views/users/new.html.erb
<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <h1>User Registration Form</h1>
  <%= form_with model: @user, url: users_path, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f| %>
    <div>
      <%= f.label :full_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', required: true %>
    </div>
    <div>
      <%= f.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.email_field :email, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', required: true %>
    </div>
    <div>
      <%= f.label :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.password_field :password, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', required: true %>
    </div>
    <div>
      <%= f.label :country_code, "Country", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.country_select :country_code, { class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' }, required: true %>
    </div>
    <div class="mt-2">
      <%= f.submit 'Register', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
    <p class="text-center text-gray-500 text-xs">Or <%= link_to "Sign in", new_session_path, class: "inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" %></p>
  <% end %>
</div>